/*
 * File: app/store/base/MyJsonStore.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DEMO.store.base.MyJsonStore', {
    extend: 'Ext.data.Store',
    requires: [
        'DEMO.model.Customer'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore',
            model: 'DEMO.model.Customer',
            proxy: {
                type: 'ajax',
                api: {  
                    read: '/cgi-bin/extdesigner/extjshandler.cgi/CustomerData/read',
                    create: '/cgi-bin/extdesigner/extjshandler.cgi/CustomerData/insert',
                    update: '/cgi-bin/extdesigner/extjshandler.cgi/CustomerData/update',
                    destroy: '/cgi-bin/extdesigner/extjshandler.cgi/CustomerData/delete'
                },
                reader: {
                    type: 'json',
                    root: 'items'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    root: 'items'
                }
            }
        }, cfg)]);
    }
});
