/*
 * File: app/controller/MyGridPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.MyGridPanel', {
    extend: 'Ext.app.Controller',

    models: [
        'Customer'
    ],
    stores: [
        'MyJsonStore'
    ],
    views: [
        'MyGridPanel'
    ],
    init: function() {
        this.control({
            "button[id=btnDelete]": {
                click: this.onDeleteClick
            },
            "button[id=btnEdit]": {
                click: this.onButtonClick
            },
            "gridview": {
                itemclick: this.onGridviewItemClick
            },
            "mygridpanel": {
                selectionchange: this.onGridviewSelectionChange
            }
        });
    },

    onDeleteClick: function(button, e, options) {
        console.log('Delete click');
    },

    onButtonClick: function(button, e, options) {
        // get selected record
        record =  button.up('gridpanel').getSelectionModel().getSelection()[0];
        view = Ext.widget('frmCustomer');
        view.getForm().loadRecord(record);
    },

    onGridviewItemClick: function(dataview, record, item, index, e, options) {
        console.log(record.data.Name);
    },

    onGridviewSelectionChange: function(model, selected, eOpts) {
        console.log('Selection change');
        if(!model.hasSelection()){
            Ext.getCmp('btnDelete').disable();
            Ext.getCmp('btnEdit').disable();
            console.Log('disabled');
        }
        else
        {
            Ext.getCmp('btnDelete').enable();
            Ext.getCmp('btnEdit').enable();
            console.log('enabled');
        };
    }

});
