/*
 * File: app/controller/CustomerGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.CustomerGrid', {
    extend: 'Ext.app.Controller',
    alias: 'controller.customergrid',

    models: [
        'Customer'
    ],
    stores: [
        'Customers'
    ],
    views: [
        'CustomerGrid'
    ],
    init: function() {
        this.control({
            "button[id=btnEdit]": {
                click: this.onEditClick
            },
            "button[id=btnRefresh]": {
                click: this.onRefreshClick
            },
            "button[id=btnInsert]": {
                click: this.onInsertClick
            },
            "button[id=btnDelete]": {
                click: this.onDeleteClick
            }
        });
    },

    onEditClick: function(button, e, options) {
        // here we get the selected record in the grid
        var grid = button.up('gridpanel');
        var customer =  grid.getSelectionModel().getSelection()[0];

        // get an instance of CustomerProperties controller and call its edit method.
        this.getController('MyApp.controller.CustomerProperties').edit(customer, grid);
    },

    onRefreshClick: function(button, e, options) {
        this.getCustomersStore().load();
    },

    onInsertClick: function(button, e, options) {
        var grid = button.up('gridpanel');

        // get an instance of CustomerProperties controller and call its insert method.
        this.getController('MyApp.controller.CustomerProperties').insert(grid);
    },

    onDeleteClick: function(button, e, options) {
        Ext.Msg.show({
            title:'Delete record?',
            msg: 'Please configrm',
            buttons: Ext.Msg.YESNO,
            icon: Ext.Msg.QUESTION,
            fn: function(btn, text) {
                if(btn == 'yes') {
                    record =  button.up('gridpanel').getSelectionModel().getSelection()[0];
                    var store = this.getCustomersStore();
                    store.remove(record);
                    store.sync();
                }
            },
            scope: this
        });
    },

    onControllerClickStub: function() {

    }

});