/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.Login', {
    extend: 'Ext.app.Controller',

    stores: [
        'User'
    ],
    views: [
        'LoginForm',
        'MainToolbar'
    ],
    init: function() {
        this.control({
            "loginform button[id=btnSubmit]": {
                click: this.onLoginClick
            },
            "maintoolbar button[id=btnLogout]": {
                click: this.onLogoutClick
            }
        });
    },

    onLoginClick: function(button, e, options) {
        this.getController('MyApp.controller.Main').showMainView();
        this.getController('MyApp.controller.User').saveSession(); 
        var win = button.up('loginform');
        win.destroy();
    },

    onLogoutClick: function(button, e, options) {
        this.getController('MyApp.controller.Main').destroyAll();
        this.getController('MyApp.controller.User').deleteSession(); 

        Ext.create('MyApp.view.LoginForm', {}).show();
    }

});
