/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Main', {
    extend: 'Ext.app.Controller',

    stores: [
        'Customers',
        'Users'
    ],
    views: [
        'MainToolbar',
        'MainTabPanel',
        'CustomerGrid',
        'UsersGrid'
    ]
,

    refs: [
        {
            ref: 'viewportmain',
            selector: 'viewportmain'
        }
    ],

    showMainView: function() {
        mainToolBar = Ext.create('MyApp.view.MainToolbar', {});
        mainView = Ext.create('MyApp.view.MainTabPanel', {flex: 1});
        var customerGrid = Ext.create('MyApp.view.CustomerGrid', {flex: 1});
        var usersGrid =  Ext.create('MyApp.view.UsersGrid', {flex: 1});
        // to be able to use "this.getViewport()" the a ref has to be added
        // please take a look at the refs section of this file.
        var center_container = this.getViewportmain().down('container[region=center]'); 
        center_container.add(mainToolBar);
        center_container.add(mainView);
        var customersTab = Ext.getCmp('customers-tab');
        var usersTab = Ext.getCmp('users-tab');
        customersTab.add(customerGrid);
        usersTab.add(usersGrid);
        // load the stores
        this.getCustomersStore().load();
        this.getUsersStore().load();
    },

    destroyAll: function() {
        mainToolBar.destroy();
        mainView.destroy();
        this.destroy();
    },

    init: function() {

    },

    onLaunch: function() {

    }

});
