/*
 * File: app/controller/User.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.User', {
    extend: 'Ext.app.Controller',

    stores: [
        'User'
    ],
    init: function() {
        this.control({
        });

        var me = this;
        var store = this.getUserStore();
        store.load();

        user = store.first();
        if(!user){
            store.add({loggedIn: false});
            user = store.first();
            store.sync();
        }

    },

    saveSession: function() {
        user.set('loggedIn', true);
        user.save();
    },

    deleteSession: function() {
        user.destroy();
        var store = this.getUserStore();
        store.sync();
    },

    getUser: function() {
        return user;
    }

});