/*
 * File: app/controller/UserProperties.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.UserProperties', {
    extend: 'Ext.app.Controller',
    alias: 'controller.userproperties',

    stores: [
        'Users'
    ],
    views: [
        'UserProperties'
    ]
,

    onOkClick: function(button, e, options) {
        var win = button.up('window');
        frm = win.down('form').getForm();
        var store = this.getUsersStore();    
        if(mode=="Insert") {
            user = frm.getValues();
            store.insert(0, user);
        }
        else
        { 
            user = frm.getRecord();
            frm.updateRecord(user);
        }
        store.sync();
        win.destroy();
    },

    onCancelClick: function(button, e, options) {
        button.up('window').destroy();
    },

    insert: function(grid) {
        // create an instance of UserProperties form
        var cp = Ext.create('MyApp.view.UserProperties', {});

        // When the user clicks the Ok button, form's data must be saved,
        // but should it do and Insert or an Update?.
        // to avoid the confusion, I'll create a variable named
        // mode, and assign Update or Insert depending on
        // what function is displaying the form. In this case
        // the function is edit, so, the variable value is Insert.

        mode="Insert";
        this.getUsersStore().setGrid(grid);

        // Show the form
        cp.show();
    },

    edit: function(user, grid) {
        // create an instance of UserProperties form
        var cp = Ext.create('MyApp.view.UserProperties', {});

        cp.down('form').getForm().loadRecord(user);

        // When the user clicks the Ok button, form's data must be saved,
        // but should it do and Insert or an Update?.
        // to avoid the confusion, I'll create a variable named
        // mode, and assign Update or Insert depending on
        // what function is displaying the form. In this case
        // the function is edit, so, the variable value is Update.

        mode="Update";
        this.getUsersStore().setGrid(grid);

        // Show the form
        cp.show();
    },

    init: function() {
        this.control({
            "button[id=btnUserOk]": {
                click: this.onOkClick
            },
            "button[id=btnUserCancel]": {
                click: this.onCancelClick
            }
        });

    },

    onLaunch: function() {

    },

    onControllerClickStub: function() {

    }

});
