/*
 * File: app/view/ui/CustomerGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.CustomerGrid', {
    extend: 'Ext.grid.Panel',

    height: 250,
    width: 400,
    title: 'Customer\'s listing',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ],
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    width: 400,
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnInsert',
                            icon: 'icons/insert.png',
                            text: 'Insert'
                        },
                        {
                            xtype: 'button',
                            id: 'btnEdit',
                            icon: 'icons/edit.png',
                            text: 'Edit'
                        },
                        {
                            xtype: 'button',
                            id: 'btnDelete',
                            icon: 'icons/delete.png',
                            text: 'Delete'
                        },
                        {
                            xtype: 'button',
                            id: 'btnRefresh',
                            icon: 'icons/refresh.png',
                            text: 'Refresh'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});