/*
 * File: app/controller/MyGridPanel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('DEMO.controller.MyGridPanel', {
    extend: 'Ext.app.Controller',
    refs: [
      {
        ref: 'background',
        selector: 'background'
      },
      {
        ref: 'mygridpanel',
        selector: 'mygridpanel'
      },
      {
        ref: 'mainview',
        selector: 'mainview'
      }
    ],

    views: ['CustomerDataForm'],
    models: ['Customer'],
    stores: ['MyJsonStore'],

    init: function() {
        me = this;
        this.control({
            "button[id=btnDelete]": {
                click: this.onDeleteClick
            },
            "button[id=btnEdit]": {
                click: this.onEditClick
            },
            "button[id=btnInsert]": {
                click: this.onInsertClick
            },
            "button[id=btnRefresh]": {
                click: this.onRefreshClick
            },
            "mainview": {
                render: this.onMainViewRender
            },

            "mygridpanel": {
                itemclick: this.onGridviewItemClick,
                selectionchange: this.onGridviewSelectionChange
            }
        });

    },

    onMainViewRender: function(){
        this.getMygridpanel().store.load();
   },

    onGridpanelRender: function(g, eopts){
        console.log('Panel Render');
        g.store.load();
    },

    onRefreshClick: function(button, e, options) {
        this.getMyJsonStoreStore().load();
    },

    onDeleteClick: function(button, e, options) {
        Ext.Msg.show({
             title:'Delete record?',
             msg: 'Please configrm',
             buttons: Ext.Msg.YESNO,
             icon: Ext.Msg.QUESTION,
             fn: function(btn, text) {
               if(btn == 'yes') {
                  record =  button.up('gridpanel').getSelectionModel().getSelection()[0];
                  var store = this.getMyJsonStoreStore();
                  console.log('aa');
                  store.remove(record);
                  console.log('bb');
                  store.sync();
                }
             },
             scope: this
        });
    },

    onEditClick: function(button, e, options) {
        // get selected record
        record =  button.up('gridpanel').getSelectionModel().getSelection()[0];
        var view = Ext.widget('frmCustomer');
        view.getForm().loadRecord(record);
        view.setInsertMode(false);
        view.show();
    },

    onInsertClick: function(button, e, options) {
        // create a new record
        var view = Ext.widget('frmCustomer');
        view.setInsertMode(true);
        view.show();
    },

    onGridviewItemClick: function(dataview, record, item, index, e, options) {
        console.log('GridViewClick');
    },

    onGridviewSelectionChange: function(model, selections, options) {
        console.log('Selection change');
        if(!model.hasSelection()){
            Ext.getCmp('btnDelete').disable();
            Ext.getCmp('btnEdit').disable();
        }
        else
        {
            Ext.getCmp('btnDelete').enable();
            Ext.getCmp('btnEdit').enable();
        };
    }
});
