/*
 * File: app/store/Customers.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Customers', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Customer'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Customers',
            model: 'MyApp.model.Customer',
            proxy: {
                type: 'ajax',
                api: {
                    read: '/cgi-bin/a_better_crm/customers/read',
                    create: '/cgi-bin/a_better_crm/customers/insert',
                    update: '/cgi-bin/a_better_crm/customers/update',
                    destroy: '/cgi-bin/a_better_crm/customers/delete'
                },
                reader: {
                    type: 'json',
                    idProperty: 'id',
                    root: 'root'
                }
            },
            listeners: {
                write: {
                    fn: me.onJsonstoreWrite,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreWrite: function(store, operation, options) {
        var customer = operation.getRecords();
        gridRef.getSelectionModel().select(customer, false);
    },

    setGrid: function(grid) {
        gridRef = grid;
    }

});