/*
 * File: app/view/ui/MyForm.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DEMO.view.ui.LoginWindow', {
    extend: 'Ext.form.Panel',

    draggable: true,
    floating: true,
    frame: true,
    id: 'loginform',
    bodyPadding: 10,
    title: 'Login form',
    modal: true,
    url: '/cgi-bin/extdesigner/extjshandler.cgi/LoginHandler/login',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: '/cgi-bin/extdesigner/extjshandler.cgi/LoginHandler/login'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    name: 'user',
                    allowBlank: false,
                    anchor: '100%',
                    selectOnFocus: true,
                    fieldLabel: 'User'
                },
                {
                    xtype: 'textfield',
                    name: 'password',
                    allowBlank: false,
                    anchor: '100%',
                    selectOnFocus: true,
                    fieldLabel: 'Password'
                }
            ]
        });

        me.callParent(arguments);
    },
  buttons: [
    {
      text: "Submit",
      type: "submit",
      action: "login",
      formBind: true
    },
    {
      text: "Cancel",
      type: "button",
      action: "cancel",
      formBind: true
    }
  ]
});

