/*
 * File: app/view/ui/MyForm.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MyForm', {
    extend: 'Ext.form.Panel',

    autoRender: true,
    autoShow: true,
    draggable: true,
    floating: true,
    frame: true,
    height: 196,
    id: 'loginform',
    width: 399,
    bodyPadding: 10,
    title: 'Login form',
    url: '/cgi-bin/extdesigner/extjshandler.cgi/LoginHandler/login',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: '/cgi-bin/extdesigner/extjshandler.cgi/LoginHandler/login'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    name: 'user',
                    fieldLabel: 'User'
                },
                {
                    xtype: 'textfield',
                    name: 'password',
                    fieldLabel: 'Password'
                },
                {
                    xtype: 'button',
                    id: 'btnSubmit',
                    text: 'Submit',
                    type: 'submit'
                },
                {
                    xtype: 'button',
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});